springdoc:
  enable-native-support: true
  api-docs:
    groups:
      enabled: true
    enabled: true
  group-configs:
    - group: chat-service
      paths-to-match:
        - /chat/**
      display-name: ChatService

    - group: auth-service
      paths-to-match:
        - /auth/**
      display-name: AuthService

    - group: club-service
      paths-to-match:
        - /club/**
      display-name: ClubService

    - group: matcher-service
      paths-to-match:
        - /matcher/**
      display-name: MatcherService

    - group: twitter-service
      paths-to-match:
        - /twitter/**
      display-name: TwitterService

  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    urls:
      - url: /auth/v3/api-docs
        name: AuthService
      - url: /chat/v3/api-docs
        name: ChatService
      - url: /matcher/v3/api-docs
        name: MatcherService
      - url: /club/v3/api-docs
        name: ClubService
      - url: /twitter/v3/api-docs
        name: TwitterService
