server:
  port: 8090
  forward-headers-strategy: framework

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
